type Carro = {
  id: number;
  nome: string;
  foto1: string;
  foto2: string;
  foto3: string;
  foto4: string;
  foto5: string;
  marca: string;
  modelo: string;
  versao: string;
  preco: string;
  anoFabricacao: number;
  anoModelo: number;
  km: string;
  motor: string;
  potencia: string;
  aceleracao: string;
  airbag: number;
  combustivel: string;
  conservacao: string;
  transmissao: string;
  placaFim: number;
  portas: number;
  cor: string;
  bancos: string;
  freios: string;
  farois: string;
  rodas: string;
  blindado: string;
  bluetooth: string;
  tetoSolar: string;
  conversivel: string;
  pilotoAutomatico: string;
  multimedia: string;
  sensorChuva: string;
  sensorEstacionamento: string;
};

export const listaCarros: Carro[] = [
    {
      id: 1,
      nome: "Ferrari 812 GTS",
      foto1: "/cars/812gts/812gts-1.jpeg",
      foto2: "/cars/812gts/812gts-2.jpeg",
      foto3: "/cars/812gts/812gts-3.jpeg",
      foto4: "/cars/812gts/812gts-4.jpeg",
      foto5: "/cars/812gts/812gts-5.jpeg",
      marca: "FERRARI",
      modelo: "812",
      versao: "GTS",
      preco: "7.600.000,00",
      anoFabricacao: 2022,
      anoModelo: 2022,
      km: "2.330",
      motor: "6.5 v12 aspirado",
      potencia: "800cv",
      aceleracao: "0 a 100 em 3 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico sequencial",
      placaFim: 4,
      portas: 2,
      cor: "Branco",
      bancos: "Couro",
      freios: "Abs com disco de ceramica nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 20’ forjadas em prata",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Sim",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
    {
      id: 2,
      nome: "Audi R8 V10 Spyder",
      foto1: "/cars/r8/r8-1.jpeg",
      foto2: "/cars/r8/r8-2.jpeg",
      foto3: "/cars/r8/r8-3.jpeg",
      foto4: "/cars/r8/r8-4.jpeg",
      foto5: "/cars/r8/r8-5.jpeg",
      marca: "AUDI",
      modelo: "R8",
      versao: "V10 Spyder",
      preco: "929.000,00",
      anoFabricacao: 2014,
      anoModelo: 2014,
      km: "8.700",
      motor: "5.2 v10 aspirado",
      potencia: "525cv",
      aceleracao: "0 a 100 em 3,8 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 7,
      portas: 2,
      cor: "Preto",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 19’ preto acetinado",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Sim",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com gps e entrada usb",
      sensorChuva: "Nao",
      sensorEstacionamento: "Camera de re/ dianteiro/ traseiro",
    },
    {
      id: 3,
      nome: "Porsche 911 Carrera",
      foto1: "/cars/911/911-1.jpeg",
      foto2: "/cars/911/911-2.jpeg",
      foto3: "/cars/911/911-3.jpeg",
      foto4: "/cars/911/911-4.jpeg",
      foto5: "/cars/911/911-5.jpeg",
      marca: "PORSCHE",
      modelo: "911",
      versao: "Carrera",
      preco: "909.000,00",
      anoFabricacao: 2022,
      anoModelo: 2023,
      km: "2.400",
      motor: "3.0 boxer biturbo 6 cil",
      potencia: "385cv",
      aceleracao: "0 a 100 em 4,2 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Pdk",
      placaFim: 6,
      portas: 2,
      cor: "Cinza",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led com pdls plus",
      rodas: "Aro 20'/21' carrera classic",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Sim",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
    {
      id: 4,
      nome: "Audi RS 6 Avant",
      foto1: "/cars/rs6/rs6-1.jpeg",
      foto2: "/cars/rs6/rs6-2.jpeg",
      foto3: "/cars/rs6/rs6-3.jpeg",
      foto4: "/cars/rs6/rs6-4.jpeg",
      foto5: "/cars/rs6/rs6-5.jpeg",
      marca: "AUDI",
      modelo: "RS 6 Avant",
      versao: "Quattro",
      preco: "829.000,00",
      anoFabricacao: 2020,
      anoModelo: 2021,
      km: "29.400",
      motor: "4.0 v8 biturbo",
      potencia: "600cv",
      aceleracao: "0 a 100 em 3,6 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automático",
      placaFim: 6,
      portas: 4,
      cor: "Preto",
      bancos: "Couro | esportivos linha RS",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 22' diamantadas",
      blindado: "Sim",
      bluetooth: "Sim",
      tetoSolar: "Sim",
      conversivel: "Não",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / câmeras 360°",
    },
    {
      id: 5,
      nome: "Porsche Taycan GTS",
      foto1: "taycan-1.jpeg",
      foto2: "taycan-2.jpeg",
      foto3: "taycan-3.jpeg",
      foto4: "taycan-4.jpeg",
      foto5: "taycan-5.jpeg",
      marca: "PORSCHE",
      modelo: "TAYCAN",
      versao: "GTS",
      preco: "850.000,00",
      anoFabricacao: 2023,
      anoModelo: 2023,
      km: "3.130",
      motor: "2 motores eletricos",
      potencia: "598cv",
      aceleracao: "0 a 100 em 3,7 seg",
      airbag: 0,
      combustivel: "Eletrico",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 2,
      portas: 4,
      cor: "Verde",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led matrix",
      rodas: "Aro 21’ rs spyder design",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Panoramico",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
    {
      id: 6,
      nome: "Mercedes-AMG SLS AMG",
      foto1: "/cars/sls/sls-1.jpeg",
      foto2: "/cars/sls/sls-2.jpeg",
      foto3: "/cars/sls/sls-3.jpeg",
      foto4: "/cars/sls/sls-4.jpeg",
      foto5: "/cars/sls/sls-5.jpeg",
      marca: "MERCEDES-AMG",
      modelo: "SLS AMG",
      versao: "",
      preco: "1.390.000,00",
      anoFabricacao: 2010,
      anoModelo: 2011,
      km: "13.000",
      motor: "6.2 v8 aspirado",
      potencia: "571cv",
      aceleracao: "0 a 100 em 3,8 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 9,
      portas: 2,
      cor: "Vermelho",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Bi-xenon",
      rodas: "Aro 19'/20' amg",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay instalado",
      sensorChuva: "Sim",
      sensorEstacionamento: "Camera de re/ dianteiro/ traseiro",
    },
    {
      id: 7,
      nome: "BMW M850i xDrive",
      foto1: "/cars/m850i/m850i-1.jpeg",
      foto2: "/cars/m850i/m850i-2.jpeg",
      foto3: "/cars/m850i/m850i-3.jpeg",
      foto4: "/cars/m850i/m850i-4.jpeg",
      foto5: "/cars/m850i/m850i-5.jpeg",
      marca: "BMW",
      modelo: "M850i",
      versao: "xDrive",
      preco: "720.000,00",
      anoFabricacao: 2019,
      anoModelo: 2020,
      km: "15.000",
      motor: "4.4 v8 biturbo",
      potencia: "530cv",
      aceleracao: "0 a 100 em 3,7 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 7,
      portas: 2,
      cor: "Laranja",
      bancos: "Couro merino",
      freios: "Abs com disco nas 4 rodas",
      farois: "Laser com led",
      rodas: "Aro 20’ em preto acetinado",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
    {
      id: 8,
      nome: "Jaguar F-Type P300 R-Dynamic",
      foto1: "/cars/f-type/f-type-1.jpeg",
      foto2: "/cars/f-type/f-type-2.jpeg",
      foto3: "/cars/f-type/f-type-3.jpeg",
      foto4: "/cars/f-type/f-type-4.jpeg",
      foto5: "/cars/f-type/f-type-5.jpeg",
      marca: "JAGUAR",
      modelo: "F-TYPE",
      versao: "P300 R-Dynamic",
      preco: "435.000,00",
      anoFabricacao: 2019,
      anoModelo: 2020,
      km: "6.400",
      motor: "2.0 4cil turbo",
      potencia: "300cv",
      aceleracao: "0 a 100 em 5,7 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 9,
      portas: 2,
      cor: "Preto",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 20'",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Panoramico",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Camera de re/ dianteiro/ traseiro",
    },
  ];
  