import imgFerrari from "./812gts/812gts-1.jpeg"

export const ferrari812 = [
    {
      nome: "Ferrari 812 GTS",
      foto1: imgFerrari[0],
      foto2: imgFerrari[1],
      foto3: imgFerrari[2],
      foto4: imgFerrari[3],
      foto5: imgFerrari[4],
      marca: "FERRARI",
      modelo: "812",
      versao: "GTS",
      preco: "7.600.000,00",
      anoFabricacao: 2022,
      anoModelo: 2022,
      km: "2.330",
      motor: "6.5 v12 aspirado",
      potencia: "800cv",
      aceleracao: "0 a 100 em 3 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico sequencial",
      placaFim: 4,
      portas: 2,
      cor: "Branco",
      bancos: "Couro",
      freios: "Abs com disco de ceramica nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 20’ forjadas em prata",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Sim",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
  ];

  export const audiR8 = [
    {
      nome: "Audi R8 V10 Spyder",
      foto1: "",
      foto2: "",
      foto3: "",
      foto4: "",
      foto5: "",
      marca: "AUDI",
      modelo: "R8",
      versao: "V10 Spyder",
      preco: "929.000,00",
      anoFabricacao: 2014,
      anoModelo: 2014,
      km: "8.700",
      motor: "5.2 v10 aspirado",
      potencia: "525cv",
      aceleracao: "0 a 100 em 3,8 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 7,
      portas: 2,
      cor: "Preto",
      garantiaDeFabrica: "Nao",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 19’ preto acetinado",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Sim",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com gps e entrada usb",
      sensorChuva: "Nao",
      sensorEstacionamento: "Camera de re/ dianteiro/ traseiro",
    },
  ];

export const porsche911 = [
    {
      nome: "Porsche 911 Carrera",
      foto1: "",
      foto2: "",
      foto3: "",
      foto4: "",
      foto5: "",
      marca: "PORSCHE",
      modelo: "911",
      versao: "Carrera",
      preco: "909.000,00",
      anoFabricacao: 2022,
      anoModelo: 2023,
      km: "2.400",
      motor: "3.0 boxer biturbo 6 cil",
      potencia: "385cv",
      aceleracao: "0 a 100 em 4,2 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Pdk",
      placaFim: 6,
      portas: 2,
      cor: "Cinza",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led com pdls plus",
      rodas: "Aro 20'/21' carrera classic",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Sim",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
  ];
  
  export const porscheTaycan = [
    {
      nome: "Porsche Taycan GTS",
      foto1: "",
      foto2: "",
      foto3: "",
      foto4: "",
      foto5: "",
      marca: "PORSCHE",
      modelo: "TAYCAN",
      versao: "GTS",
      preco: "850.000,00",
      anoFabricacao: 2023,
      anoModelo: 2023,
      km: "3.130",
      motor: "2 motores eletricos",
      potencia: "598cv",
      aceleracao: "0 a 100 em 3,7 seg",
      airbag: 0,
      combustivel: "Eletrico",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 2,
      portas: 4,
      cor: "Verde",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led matrix",
      rodas: "Aro 21’ rs spyder design",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Panoramico",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
  ];

  export const mercedesSlsAmg = [
    {
      nome: "Mercedes-AMG SLS AMG",
      foto1: "",
      foto2: "",
      foto3: "",
      foto4: "",
      foto5: "",
      marca: "MERCEDES-AMG",
      modelo: "SLS AMG",
      preco: "1.390.000,00",
      anoFabricacao: 2010,
      anoModelo: 2011,
      km: "13.000",
      motor: "6.2 v8 aspirado",
      potencia: "571cv",
      aceleracao: "0 a 100 em 3,8 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 9,
      portas: 2,
      cor: "Vermelho",
      garantiaDeFabrica: "Nao",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Bi-xenon",
      rodas: "Aro 19'/20' amg",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay instalado",
      sensorChuva: "Sim",
      sensorEstacionamento: "Camera de re/ dianteiro/ traseiro",
    },
  ];

  export const bmwM850i = [
    {
      nome: "BMW M850i xDrive",
      foto1: "",
      foto2: "",
      foto3: "",
      foto4: "",
      foto5: "",
      marca: "BMW",
      modelo: "M850i",
      versao: "xDrive",
      preco: "720.000,00",
      anoFabricacao: 2019,
      anoModelo: 2020,
      km: "15.000",
      motor: "4.4 v8 biturbo",
      potencia: "530cv",
      aceleracao: "0 a 100 em 3,7 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 7,
      portas: 2,
      cor: "Laranja",
      bancos: "Couro merino",
      freios: "Abs com disco nas 4 rodas",
      farois: "Laser com led",
      rodas: "Aro 20’ em preto acetinado",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Nao",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Dianteiro / traseiro / cameras 360°",
    },
  ];

  export const jaguarFType = [
    {
      nome: "Jaguar F-Type P300 R-Dynamic",
      foto1: "",
      foto2: "",
      foto3: "",
      foto4: "",
      foto5: "",
      marca: "JAGUAR",
      modelo: "F-TYPE",
      versao: "P300 R-Dynamic",
      preco: "435.000,00",
      anoFabricacao: 2019,
      anoModelo: 2020,
      km: "6.400",
      motor: "2.0 4cil turbo",
      potencia: "300cv",
      aceleracao: "0 a 100 em 5,7 seg",
      airbag: 0,
      combustivel: "Gasolina",
      conservacao: "Seminovo",
      transmissao: "Automatico",
      placaFim: 9,
      portas: 2,
      cor: "Preto",
      bancos: "Couro",
      freios: "Abs com disco nas 4 rodas",
      farois: "Full led",
      rodas: "Aro 20'",
      blindado: "Nao",
      bluetooth: "Sim",
      tetoSolar: "Panoramico",
      conversivel: "Nao",
      pilotoAutomatico: "Sim",
      multimedia: "Sim - com android auto e apple carplay",
      sensorChuva: "Sim",
      sensorEstacionamento: "Camera de re/ dianteiro/ traseiro",
    },
  ];
  